name: "Upload artifact"
on:
  push
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: set env
      run: |
        echo "test=12" >> "$GITHUB_ENV"


  pub:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: echo test
        run: echo ${{ env.test }}
